"""Render a ledger into a human-readable REPORT.md.

Generalized from the original make_report.py: a status table plus one section
per claim showing the numeric verdict (with the individual checks that ran) and
the literature verdict (with citations and caveats).
"""
from .ledger import Ledger

MARK = {
    "consistent": "[CONSISTENT]", "violation": "[VIOLATION]", "warn": "[WARN]",
    "supported": "[SUPPORTED]", "partially-supported": "[PARTIAL]",
    "refuted": "[REFUTED]", "uncertain": "[UNCERTAIN]",
}


def _m(verdict):
    return MARK.get(verdict, f"[{(verdict or '-').upper()}]")


def render(root):
    led = Ledger(root)
    claims = led.load_claims()
    rows = led.status_rows()

    out = [
        "# Analysis review report",
        "",
        "Each claim is reviewed on two independent tracks: a **numeric / logic** "
        "track (deterministic invariant checks over the recorded numbers) and a "
        "**literature** track (the interpretation checked against published "
        "evidence). Generated by `autoreview report`.",
        "",
        "## Status",
        "",
        "| claim | numeric | literature | confidence |",
        "|---|---|---|---|",
    ]
    for c, nv, lv in rows:
        out.append(
            f"| {c['id']} "
            f"| {_m(nv['verdict']) if nv else '-'} "
            f"| {_m(lv['verdict']) if lv else '-'} "
            f"| {lv['confidence'] if lv and lv.get('confidence') else '-'} |"
        )
    out.append("")

    for c, nv, lv in rows:
        out += [f"## {c['id']}", "", f"**Claim:** {c['claim']}", ""]
        if c.get("interpretation"):
            out += [f"**Interpretation under test:** {c['interpretation']}", ""]
        if nv:
            out += [f"**Numeric / logic** - {_m(nv['verdict'])}", ""]
            for ch in nv.get("checks", []):
                flag = "ok" if ch.get("passed") else "FAIL"
                sev = ch.get("severity", "error")
                out.append(f"- [{flag}] ({sev}) `{ch.get('id')}` "
                           f"[{ch.get('kind')}]: {ch.get('detail', '')}")
            if nv.get("notes"):
                out += ["", f"_Note:_ {nv['notes']}"]
            out.append("")
        if lv:
            out += [f"**Literature** - {_m(lv['verdict'])} "
                    f"(confidence: {lv.get('confidence', '-')})", ""]
            for cit in lv.get("citations", []):
                title = cit.get("title", "")
                year = cit.get("year", "")
                url = cit.get("url", "")
                out.append(f"- {title} ({year}). {url}")
            if lv.get("notes"):
                out += ["", f"_Caveat:_ {lv['notes']}"]
            out.append("")
        out.append("")

    text = "\n".join(out)
    (led.root / "REPORT.md").write_text(text)
    return len(claims), led.root / "REPORT.md"
