"""Render a ledger into a human-readable REPORT.md.

Generalized from the original make_report.py: a status table plus one section
per claim showing the numeric verdict (with the individual checks that ran) and
the literature verdict (with citations and caveats).
"""
from .ledger import Ledger

MARK = {
    "consistent": "[CONSISTENT]", "violation": "[VIOLATION]", "warn": "[WARN]",
    "supported": "[SUPPORTED]", "partially-supported": "[PARTIAL]",
    "refuted": "[REFUTED]", "uncertain": "[UNCERTAIN]",
}


def _m(verdict):
    return MARK.get(verdict, f"[{(verdict or '-').upper()}]")


def _deviations_section(led):
    rows = led.deviation_rows()
    if not rows:
        return []
    out = ["## Deviations & amendments", "",
           "Mid-run findings that the plan did not anticipate. A `contract` "
           "deviation is a broken assumption that gates sign-off until triaged; a "
           "`method` deviation is a local adaptation recorded for the audit trail.",
           "",
           "| id | loop | affects | kind | scope | decision | enacted |",
           "|---|---|---|---|---|---|---|"]
    for d, r in rows:
        decision = (r or {}).get("decision") or ("OPEN" if d.get("kind") == "contract" else "-")
        out.append(
            f"| {d['id']} | {d.get('loop', '-')} | {d.get('affects_step') or '-'} "
            f"| {d.get('kind')} | {d.get('scope')} | {decision} "
            f"| {(r or {}).get('enacted_in') or '-'} |")
    out.append("")
    for d, r in rows:
        out += [f"### {d['id']}", "", f"**Observed:** {d.get('observed', '')}", ""]
        if d.get("proposed_action"):
            out += [f"**Proposed action:** {d['proposed_action']}", ""]
        if r:
            line = f"**Resolution:** {r.get('decision')}"
            if r.get("enacted_in"):
                line += f" (enacted in {r['enacted_in']})"
            if r.get("by"):
                line += f" — by {r['by']}"
            out += [line, ""]
            if r.get("notes"):
                out += [f"_Note:_ {r['notes']}", ""]
        elif d.get("kind") == "contract":
            out += ["**Resolution:** _OPEN — blocks sign-off until triaged._", ""]
    out.append("")
    return out


def render(root):
    led = Ledger(root)
    claims = led.load_claims()
    rows = led.status_rows()

    out = [
        "# Analysis review report",
        "",
        "Each claim is reviewed on two independent tracks: a **numeric / logic** "
        "track (deterministic invariant checks over the recorded numbers) and a "
        "**literature** track (the interpretation checked against published "
        "evidence). Generated by `autoreview report`.",
        "",
        "## Status",
        "",
        "| claim | numeric | literature | confidence |",
        "|---|---|---|---|",
    ]
    for c, nv, lv in rows:
        out.append(
            f"| {c['id']} "
            f"| {_m(nv['verdict']) if nv else '-'} "
            f"| {_m(lv['verdict']) if lv else '-'} "
            f"| {lv['confidence'] if lv and lv.get('confidence') else '-'} |"
        )
    out.append("")

    out += _deviations_section(led)

    for c, nv, lv in rows:
        head = f"## {c['id']}"
        if c.get("loop") and c["loop"] != 1:
            head += f"  _(loop {c['loop']})_"
        out += [head, "", f"**Claim:** {c['claim']}", ""]
        if c.get("interpretation"):
            out += [f"**Interpretation under test:** {c['interpretation']}", ""]
        if nv:
            out += [f"**Numeric / logic** - {_m(nv['verdict'])}", ""]
            for ch in nv.get("checks", []):
                flag = "ok" if ch.get("passed") else "FAIL"
                sev = ch.get("severity", "error")
                out.append(f"- [{flag}] ({sev}) `{ch.get('id')}` "
                           f"[{ch.get('kind')}]: {ch.get('detail', '')}")
            if nv.get("notes"):
                out += ["", f"_Note:_ {nv['notes']}"]
            out.append("")
        if lv:
            out += [f"**Literature** - {_m(lv['verdict'])} "
                    f"(confidence: {lv.get('confidence', '-')})", ""]
            for cit in lv.get("citations", []):
                title = cit.get("title", "")
                year = cit.get("year", "")
                url = cit.get("url", "")
                out.append(f"- {title} ({year}). {url}")
            if lv.get("notes"):
                out += ["", f"_Caveat:_ {lv['notes']}"]
            out.append("")
        out.append("")

    text = "\n".join(out)
    (led.root / "REPORT.md").write_text(text)
    return len(claims), led.root / "REPORT.md"
