"""Assemble claims.jsonl + verdicts.jsonl into a human-readable REPORT.md."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent))
from claimlog import load_claims, load_verdicts

HERE = Path(__file__).parent
claims = load_claims()
verdicts = load_verdicts()


def vfor(cid, chash, kind):
    for v in verdicts:
        if v["id"] == cid and v["hash"] == chash and v["kind"] == kind:
            return v
    return None


EMO = {"supported": "[SUPPORTED]", "partially-supported": "[PARTIAL]",
       "refuted": "[REFUTED]", "uncertain": "[UNCERTAIN]",
       "reproduced": "[REPRODUCED]", "MISMATCH": "[MISMATCH]", "CHECK": "[CHECK]"}

lines = ["# Claim verification report",
         "",
         "Each analysis claim is split into a **data fact** (recomputed from the h5ad by "
         "`verify_data.py` - never trusting the quoted number) and a **biological "
         "interpretation** (checked against published literature by verifier agents). "
         "Generated by `make_report.py`.",
         ""]

# status table
lines += ["## Status", "", "| claim | data | literature | confidence |", "|---|---|---|---|"]
for c in claims:
    dv = vfor(c["id"], c["hash"], "data")
    lv = vfor(c["id"], c["hash"], "literature")
    lines.append(f"| {c['id']} | {EMO.get(dv['verdict'], dv['verdict']) if dv else '-'} "
                 f"| {EMO.get(lv['verdict'], lv['verdict']) if lv else '-'} "
                 f"| {lv['confidence'] if lv else '-'} |")
lines.append("")

for c in claims:
    lines += [f"## {c['id']}", "", f"**Claim:** {c['claim']}", ""]
    if c.get("bio_assertion"):
        lines += [f"**Biological interpretation under test:** {c['bio_assertion']}", ""]
    dv = vfor(c["id"], c["hash"], "data")
    if dv:
        lines += [f"**Data check** - {EMO.get(dv['verdict'], dv['verdict'])}: {dv.get('notes','')}", ""]
    lv = vfor(c["id"], c["hash"], "literature")
    if lv:
        lines += [f"**Literature** - {EMO.get(lv['verdict'], lv['verdict'])} "
                  f"(confidence: {lv['confidence']})", ""]
        for cit in lv.get("citations", []):
            lines.append(f"- {cit['title']} ({cit.get('year','')}). {cit['url']}")
        if lv.get("notes"):
            lines += ["", f"_Caveat:_ {lv['notes']}"]
        lines.append("")
    lines.append("")

(HERE / "REPORT.md").write_text("\n".join(lines))
print(f"wrote {HERE / 'REPORT.md'} ({len(claims)} claims)")
